# Generated by Django 3.1.1 on 2020-09-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, null=True, verbose_name='اللون المفضل')),
                ('subject', models.CharField(max_length=100, null=True, verbose_name='المادة الاكاديمية المفضلة')),
                ('fruite', models.CharField(max_length=100, null=True, verbose_name='الفاكهة المفضلة')),
                ('movie', models.CharField(max_length=100, null=True, verbose_name='نوع الافلام المفضلة ')),
                ('hobby', models.CharField(max_length=100, null=True, verbose_name='الهواية المفضلة')),
                ('social', models.CharField(max_length=100, null=True, verbose_name='هل انت اجتماعي')),
                ('team', models.CharField(max_length=100, null=True, verbose_name='الفريق العالمي المفضل')),
            ],
        ),
    ]
