# Generated by Django 3.1.1 on 2020-09-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personality',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('green', 'green'), ('black', 'black'), ('yellow', 'yellow'), ('blue', 'blue'), ('orange', 'orange')], max_length=100, null=True, verbose_name='اللون المفضل'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='fruite',
            field=models.CharField(choices=[('orange', 'orange'), ('banana', 'banana'), ('mango', 'mango'), ('yosfi', 'yosfi'), ('watermelon', 'watermelon'), ('blueberry', 'blueberry')], max_length=100, null=True, verbose_name='الفاكهة المفضلة'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='hobby',
            field=models.CharField(choices=[('painting', 'painting'), ('football', 'football'), ('reading', 'reading'), ('gaming', 'gaming'), ('other_sport', 'other_sport')], max_length=100, null=True, verbose_name='الهواية المفضلة'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='movie',
            field=models.CharField(choices=[('horror', 'horror'), ('comedy', 'comedy'), ('action', 'action'), ('romance', 'romance')], max_length=100, null=True, verbose_name='نوع الافلام المفضلة '),
        ),
        migrations.AlterField(
            model_name='personality',
            name='social',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='personality',
            name='subject',
            field=models.CharField(choices=[('math', 'math'), ('physics', 'physics'), ('history', 'history'), ('french', 'french'), ('english', 'english'), ('arabic', 'arabic')], max_length=100, null=True, verbose_name='المادة الاكاديمية المفضلة'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='team',
            field=models.CharField(choices=[('liverpool', 'liverpool'), ('real-madrid', 'real-madrid'), ('barca', 'barca'), ('juventus', 'juventus'), ('man-united', 'man-united'), ('man-city', 'man-city'), ('atletico-madrid', 'atletico-madrid'), ('arsenal', 'arsenal')], max_length=100, null=True, verbose_name='الفريق العالمي المفضل'),
        ),
    ]
