# Generated by Django 3.1.1 on 2020-09-19 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personality', '0002_auto_20200919_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='personality',
            name='age',
            field=models.CharField(max_length=50, null=True, verbose_name='العمر'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='social',
            field=models.BooleanField(null=True, verbose_name='هل انت اجتماعي'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
