# Generated by Django 3.1.1 on 2020-09-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0003_auto_20200919_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='facebooklink',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Facebook Profile Link (optional)'),
        ),
    ]
