# Generated by Django 3.1.1 on 2020-09-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0006_personality_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personality',
            name='img',
        ),
    ]
