# Generated by Django 3.1.1 on 2020-09-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0008_personality_facebook_profile_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='personality',
            name='singer',
            field=models.CharField(max_length=150, null=True, verbose_name='المغني العربي المفضل'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='movie',
            field=models.CharField(choices=[('horror', 'horror'), ('comedy', 'comedy'), ('action', 'action'), ('romance', 'romance'), ('science fiction', 'science fiction')], max_length=100, null=True, verbose_name='نوع الافلام المفضلة '),
        ),
    ]
