# Generated by Django 3.1.1 on 2020-09-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0009_auto_20200923_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='personality',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
